### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by quimnut** [MeshAddicts/meshinfo#8]
Hey, this is cool, thanks.

I have the desire for unicode but the arduino json currently does not support it. I was going a different path with a preprocessing solution of sorts. 

Anyway i quickly knocked this up from what I've found and thought I'd share. 

https://gist.github.com/quimnut/c5ae707c627ed5434b300f6e8a40ccf7

**Comment by kevinelliott** [comment]
Hey! You're welcome. So that's interesting and very helpful. Let me take a look and see about implementing! (If you feel up to it, would take a PR too).

**Comment by kevinelliott** [comment]
Waiting for https://github.com/meshtastic/firmware/issues/3562 to be resolved.

My suspicion is that https://github.com/meshtastic/firmware/blob/master/src/mqtt/JSONValue.cpp#L854-L863 has something not quite right, since it is sending `\u0000` instead of the specific unicode value to MQTT JSON.

**Comment by quimnut** [comment]
It was valid unicode, needed to load it as utf-16-le. I have a couple of message types to get working, after that can try merge the protobufs stuff.

**Comment by kevinelliott** [comment]
@quimnut Protobuf support is in place! And unicode is working great for that. However, JSON messages will still not support unicode properly, because it's broken in the firmware (see https://github.com/meshtastic/firmware/issues/3562).

That said, the bulk of messages are protobufs, so this seems to have resolved support! Thanks @quimnut ...
